name: shopping_app_delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
 
  
  
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  
  
  
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  
  shared_preferences: ^2.2.3
 
  

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/img/

    
